### ISSUE TITLE
TokenCustomerID validation error when saving updated billing details for recurring payment

### ISSUE THREAD

**Issue by AsylumSeekersCentre** [agileware/au.com.agileware.ewayrecurring#15] opened 2021-04-29 06:51 UTC
Steps to reproduce:

- Path 1:
  - Navigate to a contact who has an active (preferably test) recurring payment which uses the ewayrecurring payment processor
  - Click More -> Change Billing Details next to the recurring payment record in the Recurring Contributions tab
  - Click Add Credit Card
  - Add (test) credit card details in eWay
  - Click OK in the Civi dialog to update the credit card list
  - Select the new credit card and press Save
- Path 2:
  - Navigate to Change Billing Details as before
  - Select a previously-saved credit card
  - press Save

Symptoms:

On our Test and Production sites, both of these paths produce an ever-spinning triangle. When reloading the page, Civi displays a popup message "Error: TokenCustomerID Required". However, the selected credit card details do appear to have updated in the database (civicrm_contribution_recur.payment_token_id has changed).

Affected systems:

This happens on our production site and also a test site running a clean copy of Civi. In both cases the Civi version is 5.33.5 and the ewayrecurring version is 2.3.9.

Possible patch:

The behaviour seems to improve slightly (or at least it's different) after this patch:
https://github.com/AsylumSeekersCentre/au.com.agileware.ewayrecurring/commit/fb0e1ced97e975a9847e422d97de75538601709d

Caveats:

With this patch in place, updating the billing details to use a previously-saved credit card (Path 2) now produces a redirect to eWay when pressing Save (but also seems to save the details, I just close the eWay window). Without this patch, this procedure produces an ever-spinning triangle but no redirect to eWay. I think the database is updated in either case.

Closing thoughts:

Is the issue simply cosmetic? Can we trust the saved token to work despite this error message? Are other sites affected or have I missed something in the setup of the test site?

**Comment by agileware-fj** [comment] 2021-04-29 07:21
Thanks for the report and partial solution.  We've definitely seen this on correctly set up sites, but only recently.

The problem here is partially with the following call to updateCustomer.  I'm not sure if we actually even want to be making this call, and if we do (to update the billing address details on eWAY), the bit that opens an eWAY page also needs to be changed to one of the background methods - as we don't need to collect credit card details at this stage having already done it.

So we can do one of the following:
1. Implement that patch *and* change the updateCustomer call to Eway\Rapid\Enum\ApiMethod::DIRECT
2. Remove the updateCustomer call and not update the billing address on eWAY

Thoughts?

**Comment by AsylumSeekersCentre** [comment] 2021-04-29 10:05
I've checked with our fundraising team, and they do not need the billing address updated in eWay at this point. So I'd say either solution is fine from our perspective.

**Comment by agileware-fj** [comment] 2021-05-03 07:44
I've created the option 2 fix, which removes the "TokenCustomerID Required" message, however while testing I could not confirm the recurring contribution's token being updated, either with or without the fix in place.

**Comment by AsylumSeekersCentre** [comment] 2021-05-04 00:20
I've tested this change (branch CIVIEWAY-212) and from my perspective it seems good.

After saving the updated details, if I click "change billing details" again, the updated details are not selected by default. I haven't found anything in the code which would select the current card, but I only had a quick look. When I look at the database records, they appear to have updated correctly. I used a query like this to inspect the database records (having updated the details for contact ID 20):

`select civicrm_contribution_recur.contact_id, civicrm_payment_token.contact_id, payment_token_id, masked_account_number from civicrm_contribution_recur join civicrm_payment_token on civicrm_payment_token.id = payment_token_id where civicrm_contribution_recur.contact_id=20;`

The masked_account_number changes to the correct value each time I update the card, so I think it is working correctly.

**Comment by AsylumSeekersCentre** [comment] 2021-05-04 03:36
Another detail which might be worth noting: sometimes when adding a new card, the eWay tab redirects to a page on my site with just this text on a white background:

{"is_error":1,"message":"no token."}

The URL at this point is: <mytest.site>/civicrm/ewayrecurring/savetoken?cid=20&pp_id=2&AccessCode=<code>

If I switch back to the Civi tab and press OK, the card is there and saving works. I've seen this issue appear while testing, and then later it has disappeared by itself. I don't know if it's related to this issue, I've been assuming it's an intermittent issue at eWay's end and that I can safely ignore it (just because it seems to come and go without me changing anything).

**Comment by agileware-fj** [comment] 2021-05-04 04:31
Thanks for the thorough feedback @AsylumSeekersCentre 

I can confirm that nothing was in place to select the correct card in the UI, and have fixed that. The token not appearing to be updated was due to uncleaned previous test data here, so not actually a probably.

The fix for this is part of the 2.3.10 release.

**Closed by agileware-fj** 2021-05-04 04:31 UTC
